#!/bin/bash
#=======================================================================
#
#          FILE:  sensors
#				  bash-script for Openmediavault
#
#         USAGE:  install it with install.sh
#
#   DESCRIPTION:  it creates
#
#        AUTHOR:  Solo0815, thx to all Users of the OMV-Forums,
#                 who added sample rrd-scripts
#                 feel free to edit this file, but please share it in
#                 the OMV-Forum:
#                 http://forums.openmediavault.org/viewtopic.php?f=13&t=79#p244
#       VERSION:  0.3
#=======================================================================

# Todo:
# - bug testing

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_COLLECTD_CONFIG=${OMV_COLLECTD_CONFIG:-"/etc/collectd/collectd.conf"}
OMV_COLLECTD_RRDTOOL_MKGRAPH=${OMV_COLLECTD_RRDTOOL_MKGRAPH:-"/usr/sbin/omv-mkgraph"}
#Mahmoud <mahmud1@hotmail.com> Oct 2013: Following line fixed to meet OMV 0.5
OMV_JSFILE_BASEDIR="/var/www/openmediavault/js/omv/module/admin/diagnostic/system"
OMV_JSFILE_PLUGINDIR="/var/www/openmediavault/js/omv/module/admin/diagnostic/system/plugin"

# simple log-function
_log() {
			[[ "$*" =~ ^([A-Za-z]*):\ (.*) ]] && 
			{
			PRIORITY=${BASH_REMATCH[1]}
			LOGMESSAGE=${BASH_REMATCH[2]}
			[[ "$(basename "$0")" =~ ^([A-Za-z]*) ]] &&
			LOGMESSAGE="${BASH_REMATCH[1]}[$$]: $PRIORITY: '$LOGMESSAGE'";
			logger -p local6.$PRIORITY "$LOGMESSAGE"
			echo "$LOGMESSAGE"
			echo "# $(date '+%b %e %H:%M:%S') - $LOGMESSAGE" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
			}
}

# Begin sensors section in /usr/sbin/omv-mkgraph
f_begin_section() {
	echo -e "# <<< [openmediavault] sensors-script" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
}

# End sensors section in /usr/sbin/omv-mkgraph
f_end_section() {
	echo "# >>> [openmediavault] sensors-script" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
}

# hedader for sensors section in /usr/sbin/omv-mkgraph
f_plugin_sensors_header() {
cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
# Plugin: sensors
TITLE_LOAD="CPU temperature"
COLOR_CPU_CORE_0="#0000fd" # blue
COLOR_CPU_CORE_1="#ff0000" # red

EOF
}

# hedader for fanspeed section in /usr/sbin/omv-mkgraph
f_plugin_fanspeed_header() {
cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
# Plugin: fanspeed
TITLE_LOAD="Fan Speed"
COLOR_FANSPEED="#00cc00" # green

EOF
}

# hedader for fanspeed section in /usr/sbin/omv-mkgraph
f_plugin_hddtemp_header() {
cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
# Plugin: hddtemp
TITLE_HDD="Hard Drive Temperature"
COLOR_HDD1="#0000FD" # BLUE
COLOR_HDD2="#FF0000" # RED
COLOR_HDD3="#00CC00" # GREEN
COLOR_HDD4="#00FFFF" # CYAN
COLOR_HDD5="#FF00FF" # PINK
COLOR_HDD6="#FFFF00" # YELLOW

EOF
}


# rrdtool script for fanspeed
f_fanspeedrrd() {
cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
rrdtool graph \${IMGDIR}/fanspeed-hour.png --start \${HOURSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${HOURTITLE}" --slope-mode --upper-limit 2000 --lower-limit 0 --units-exponent 0 \
DEF:fan1avg=\${DATA}/$FANSPEED:value:AVERAGE \
DEF:fan1pmin=\${DATA}/$FANSPEED:value:MIN \
DEF:fan1pmax=\${DATA}/$FANSPEED:value:MAX \
LINE1:fan1avg\${COLOR_FANSPEED}:"Fan Speed" \
GPRINT:fan1pmin:MIN:"%4.2lf Min" \
GPRINT:fan1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:fan1pmax:MAX:"%4.2lf Max" \
GPRINT:fan1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/fanspeed-day.png --start \${DAYSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${DAYTITLE}" --slope-mode --upper-limit 2000 --lower-limit 0 --units-exponent 0 \
DEF:fan1avg=\${DATA}/$FANSPEED:value:AVERAGE \
DEF:fan1pmin=\${DATA}/$FANSPEED:value:MIN \
DEF:fan1pmax=\${DATA}/$FANSPEED:value:MAX \
LINE1:fan1avg\${COLOR_FANSPEED}:"Fan Speed" \
GPRINT:fan1pmin:MIN:"%4.2lf Min" \
GPRINT:fan1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:fan1pmax:MAX:"%4.2lf Max" \
GPRINT:fan1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/fanspeed-week.png --start \${WEEKSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${WEEKTITLE}" --slope-mode --upper-limit 2000 --lower-limit 0 --units-exponent 0 \
DEF:fan1avg=\${DATA}/$FANSPEED:value:AVERAGE \
DEF:fan1pmin=\${DATA}/$FANSPEED:value:MIN \
DEF:fan1pmax=\${DATA}/$FANSPEED:value:MAX \
LINE1:fan1avg\${COLOR_FANSPEED}:"Fan Speed" \
GPRINT:fan1pmin:MIN:"%4.2lf Min" \
GPRINT:fan1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:fan1pmax:MAX:"%4.2lf Max" \
GPRINT:fan1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/fanspeed-month.png --start \${MONTHSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${MONTHTITLE}" --slope-mode --upper-limit 2000 --lower-limit 0 --units-exponent 0 \
DEF:fan1avg=\${DATA}/$FANSPEED:value:AVERAGE \
DEF:fan1pmin=\${DATA}/$FANSPEED:value:MIN \
DEF:fan1pmax=\${DATA}/$FANSPEED:value:MAX \
LINE1:fan1avg\${COLOR_FANSPEED}:"Fan Speed" \
GPRINT:fan1pmin:MIN:"%4.2lf Min" \
GPRINT:fan1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:fan1pmax:MAX:"%4.2lf Max" \
GPRINT:fan1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/fanspeed-year.png --start \${YEARSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${YEARTITLE}" --slope-mode --upper-limit 2000 --lower-limit 0 --units-exponent 0 \
DEF:fan1avg=\${DATA}/$FANSPEED:value:AVERAGE \
DEF:fan1pmin=\${DATA}/$FANSPEED:value:MIN \
DEF:fan1pmax=\${DATA}/$FANSPEED:value:MAX \
LINE1:fan1avg\${COLOR_FANSPEED}:"Fan Speed" \
GPRINT:fan1pmin:MIN:"%4.2lf Min" \
GPRINT:fan1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:fan1pmax:MAX:"%4.2lf Max" \
GPRINT:fan1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null

EOF
}

# rrdtool script for one sensor
f_one_sensorrrd() {
cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
rrdtool graph \${IMGDIR}/sensors-hour.png --start \${HOURSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${HOURTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-day.png --start \${DAYSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${DAYTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-week.png --start \${WEEKSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${WEEKTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-month.png --start \${MONTHSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${MONTHTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-year.png --start \${YEARSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${YEARTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null

EOF
}

# rrdtool script for two sensors
f_two_sensorsrrd() {
cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
rrdtool graph \${IMGDIR}/sensors-hour.png --start \${HOURSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${HOURTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
DEF:cpuc1avg=\${DATA}/$SENSOR2:value:AVERAGE \
DEF:cpuc1min=\${DATA}/$SENSOR2:value:MIN \
DEF:cpuc1max=\${DATA}/$SENSOR2:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
LINE1:cpuc1avg\${COLOR_CPU_CORE_1}:"Core 2" \
GPRINT:cpuc1min:MIN:"%4.2lf Min" \
GPRINT:cpuc1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc1max:MAX:"%4.2lf Max" \
GPRINT:cpuc1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-day.png --start \${DAYSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${DAYTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
DEF:cpuc1avg=\${DATA}/$SENSOR2:value:AVERAGE \
DEF:cpuc1min=\${DATA}/$SENSOR2:value:MIN \
DEF:cpuc1max=\${DATA}/$SENSOR2:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
LINE1:cpuc1avg\${COLOR_CPU_CORE_1}:"Core 2" \
GPRINT:cpuc1min:MIN:"%4.2lf Min" \
GPRINT:cpuc1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc1max:MAX:"%4.2lf Max" \
GPRINT:cpuc1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-week.png --start \${WEEKSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${WEEKTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
DEF:cpuc1avg=\${DATA}/$SENSOR2:value:AVERAGE \
DEF:cpuc1min=\${DATA}/$SENSOR2:value:MIN \
DEF:cpuc1max=\${DATA}/$SENSOR2:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
LINE1:cpuc1avg\${COLOR_CPU_CORE_1}:"Core 2" \
GPRINT:cpuc1min:MIN:"%4.2lf Min" \
GPRINT:cpuc1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc1max:MAX:"%4.2lf Max" \
GPRINT:cpuc1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-month.png --start \${MONTHSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${MONTHTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
DEF:cpuc1avg=\${DATA}/$SENSOR2:value:AVERAGE \
DEF:cpuc1min=\${DATA}/$SENSOR2:value:MIN \
DEF:cpuc1max=\${DATA}/$SENSOR2:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
LINE1:cpuc1avg\${COLOR_CPU_CORE_1}:"Core 2" \
GPRINT:cpuc1min:MIN:"%4.2lf Min" \
GPRINT:cpuc1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc1max:MAX:"%4.2lf Max" \
GPRINT:cpuc1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/sensors-year.png --start \${YEARSTART} \${DEFAULTS} --title "\${TITLE_LOAD}\${YEARTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
DEF:cpuc0avg=\${DATA}/$SENSOR1:value:AVERAGE \
DEF:cpuc0min=\${DATA}/$SENSOR1:value:MIN \
DEF:cpuc0max=\${DATA}/$SENSOR1:value:MAX \
DEF:cpuc1avg=\${DATA}/$SENSOR2:value:AVERAGE \
DEF:cpuc1min=\${DATA}/$SENSOR2:value:MIN \
DEF:cpuc1max=\${DATA}/$SENSOR2:value:MAX \
LINE1:cpuc0avg\${COLOR_CPU_CORE_0}:"Core 1" \
GPRINT:cpuc0min:MIN:"%4.2lf Min" \
GPRINT:cpuc0avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc0max:MAX:"%4.2lf Max" \
GPRINT:cpuc0avg:LAST:"%4.2lf Last\l" \
LINE1:cpuc1avg\${COLOR_CPU_CORE_1}:"Core 2" \
GPRINT:cpuc1min:MIN:"%4.2lf Min" \
GPRINT:cpuc1avg:AVERAGE:"%4.2lf Avg" \
GPRINT:cpuc1max:MAX:"%4.2lf Max" \
GPRINT:cpuc1avg:LAST:"%4.2lf Last\l" \
COMMENT:"\${LASTUPDATE}" >/dev/null

EOF
}

# rrdtool script for HDD tempteratures
f_hdd_sensorsrrd() {

RDD_DEF=""
RDD_LINE=""
for i in $(seq 1 $NUM_HDD)
do
	eval RDD_DEF+="DEF:hdd${i}avg=\\\${DATA}/\${HDD${i}}:value:AVERAGE\ "
	eval RDD_DEF+="DEF:hdd${i}min=\\\${DATA}/\${HDD${i}}:value:MIN\ "
	eval RDD_DEF+="DEF:hdd${i}max=\\\${DATA}/\${HDD${i}}:value:MAX\ "
done

for i in $(seq 1 $NUM_HDD)
do
	RDD_LINE+="LINE1:hdd${i}avg\${COLOR_HDD${i}}:\"HDD ${i}\" "
	RDD_LINE+="GPRINT:hdd${i}min:MIN:\"%4.2lf Min\" "
	RDD_LINE+="GPRINT:hdd${i}avg:AVERAGE:\"%4.2lf Avg\" "
	RDD_LINE+="GPRINT:hdd${i}max:MAX:\"%4.2lf Max\" "
	RDD_LINE+="GPRINT:hdd${i}avg:LAST:\"%4.2lf Last\l\" "
done

cat <<EOF >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
rrdtool graph \${IMGDIR}/hddtemp-hour.png --start \${HOURSTART} \${DEFAULTS} --title "\${TITLE_HDD}\${HOURTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
$RDD_DEF \
$RDD_LINE \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/hddtemp-day.png --start \${DAYSTART} \${DEFAULTS} --title "\${TITLE_HDD}\${DAYTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
$RDD_DEF \
$RDD_LINE \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/hddtemp-week.png --start \${WEEKSTART} \${DEFAULTS} --title "\${TITLE_HDD}\${WEEKTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
$RDD_DEF \
$RDD_LINE \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/hddtemp-month.png --start \${MONTHSTART} \${DEFAULTS} --title "\${TITLE_HDD}\${MONTHTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
$RDD_DEF \
$RDD_LINE \
COMMENT:"\${LASTUPDATE}" >/dev/null
rrdtool graph \${IMGDIR}/hddtemp-year.png --start \${YEARSTART} \${DEFAULTS} --title "\${TITLE_HDD}\${YEARTITLE}" --slope-mode --upper-limit 80 --lower-limit 0 --units-exponent 0 \
$RDD_DEF \
$RDD_LINE \
COMMENT:"\${LASTUPDATE}" >/dev/null

EOF
}

######################################################################
# Main body of script
######################################################################

# Remove existing js-files, they are newly created later
if [ -f "$OMV_JSFILE_BASEDIR/Sensors.js" ]; then
	rm "$OMV_JSFILE_BASEDIR/Sensors.js" > /dev/null 2>&1
fi
if [ -f "$OMV_JSFILE_PLUGINDIR/Fanspeed.js" ]; then
	rm "$OMV_JSFILE_PLUGINDIR/Fanspeed.js" > /dev/null 2>&1
fi
if [ -f "$OMV_JSFILE_PLUGINDIR/Temps.js" ]; then
	rm "$OMV_JSFILE_PLUGINDIR/Temps.js" > /dev/null 2>&1
fi
if [ -f "$OMV_JSFILE_PLUGINDIR/HDDTemp.js" ]; then
	rm "$OMV_JSFILE_PLUGINDIR/HDDTemp.js" > /dev/null 2>&1
fi

sed -i /LoadPlugin\ sensors/d ${OMV_COLLECTD_CONFIG} 2> /dev/null

sed -i /LoadPlugin\ hddtemp/d ${OMV_COLLECTD_CONFIG} 2> /dev/null

# LoadPlugin fanspeed is already part of collectd - if it exists -> remove it!
sed -i /LoadPlugin\ fanspeed/d ${OMV_COLLECTD_CONFIG} 2> /dev/null

# Deletes the existing section of the sensors-script
sed -i '/#\ <<<\ \[openmediavault\]\ sensors-script/,/#\ >>>\ \[openmediavault\]\ sensors-script/d' $OMV_COLLECTD_RRDTOOL_MKGRAPH

# begin new sensor-section in omv-mkgraph
f_begin_section

# Checking config-file
# The config-file is /etc/omv-sensor.conf
if [ -f /etc/omv-sensor.conf ]; then
	. /etc/omv-sensor.conf
else
	_log "WARN: /etc/omv-sensor.conf not found - exiting"
	f_end_section
	exit 1
fi

# Add "LoadPlugin sensors" to /etc/collectd/collectd.conf
if ! egrep "^LoadPlugin sensors" ${OMV_COLLECTD_CONFIG} 2> /dev/null; then
	echo -e "LoadPlugin sensors\n" >> ${OMV_COLLECTD_CONFIG}
fi

if ! egrep "^LoadPlugin hddtemp" ${OMV_COLLECTD_CONFIG} 2> /dev/null; then
	echo -e "LoadPlugin hddtemp\n" >> ${OMV_COLLECTD_CONFIG}
fi

# Checking config
[[ "$pluginconf" =~ ^([1-4])$ ]] || {
			_log "WARN: Invalid parameter format: pluginconf"
			_log "WARN: You set it to '$pluginconf', which is not a correct syntax. Only '1' - '4' is allowed."
			_log "WARN: Setting pluginconf to 1 - one sensor, no fanspeed"
			pluginconf="1"; }

[[ -f /var/lib/rrdcached/db/localhost/$SENSOR1 ]] || {
	_log "WARN: given rrd-file in /var/lib/rrdcached/db/localhost for SENSOR1 does not exist"
	_log "WARN: You set it to $SENSOR1"
	_log "WARN: Pleast check your config-file"
	_log "WARN: exiting script ..."
	f_end_section
	exit 1
	}

if [ ! -z "$SENSOR2" ]; then
	[[ -f /var/lib/rrdcached/db/localhost/$SENSOR2 ]] || {
	_log "WARN: given rrd-file in /var/lib/rrdcached/db/localhost for SENSOR2 does not exist"
	_log "WARN: You set it to $SENSOR2"
	_log "WARN: Pleast check your config-file"
	_log "WARN: exiting script ..."
	f_end_section
	exit 1
	}
fi

if [ ! -z "$FANSPEED" ]; then
	[[ -f /var/lib/rrdcached/db/localhost/$FANSPEED ]] || {
	_log "WARN: given rrd-file in /var/lib/rrdcached/db/localhost for FANSPEED does not exist"
	_log "WARN: You set it to $FANSPEED"
	_log "WARN: Pleast check your config-file"
	_log "WARN: exiting script ..."
	f_end_section
	exit 1
	}
fi

#copy base tab file
cp "$OMV_JSFILE_BASEDIR/Sensors.default" "$OMV_JSFILE_BASEDIR/Sensors.js"

# Which configuration is selected?
case $pluginconf in
	1)
		echo "# config: 1 = one sensor, no fanspeed" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
		cp "$OMV_JSFILE_PLUGINDIR/Sensors.default" "$OMV_JSFILE_PLUGINDIR/Temps.js"
		f_plugin_sensors_header
		f_one_sensorrrd
		;;
	2)
		echo "# config: 2 = two sensors, no fanspeed" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
		if [ -z "$SENSOR2" ]; then
			_log "WARN: SENSOR2 not defined - exiting"
			
		else
			cp "$OMV_JSFILE_PLUGINDIR/Sensors.default" "$OMV_JSFILE_PLUGINDIR/Temps.js"
			f_plugin_sensors_header
			f_two_sensorsrrd
		fi
		;;
	3)
		echo "# config: 3 = one sensor and fanspeed" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
		cp "$OMV_JSFILE_PLUGINDIR/Sensors.default" "$OMV_JSFILE_PLUGINDIR/Temps.js"
		f_plugin_sensors_header
		f_one_sensorrrd

		if [ -z "$FANSPEED" ]; then
			_log "WARN: FANSPEED not defined - exiting"
			echo "# FANSPEED not defined - exiting" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
		else
			cp "$OMV_JSFILE_PLUGINDIR/Fanspeed.default" "$OMV_JSFILE_PLUGINDIR/Fanspeed.js"
			f_plugin_fanspeed_header
			f_fanspeedrrd
		fi
		;;
	4)
		echo "# config: 4 = two sensors and fanspeed" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
		if [ -z "$SENSOR2" ]; then
			_log "WARN: SENSOR2 not defined - exiting"
			echo "# SENSOR2 not defined - exiting" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
		else
			cp "$OMV_JSFILE_PLUGINDIR/Sensors.default" "$OMV_JSFILE_PLUGINDIR/Temps.js"
			
			f_plugin_sensors_header
			f_two_sensorsrrd
		fi

		if [ -z "$FANSPEED" ]; then
			_log "WARN: FANSPEED not defined - exiting"
			echo "# FANSPEED not defined - exiting" >> ${OMV_COLLECTD_RRDTOOL_MKGRAPH}
		else
			cp "$OMV_JSFILE_PLUGINDIR/Fanspeed.default" "$OMV_JSFILE_PLUGINDIR/Fanspeed.js"
			f_plugin_fanspeed_header
			f_fanspeedrrd
		fi
		;;
	*)
		_log "INFO: This should not happen"
		exit 1
		;;
esac

# Checking hddtemp config
[[ "$NUM_HDD" =~ ^([[:digit:]]+)$ ]] || {
			_log "WARN: Invalid parameter format: NUM_HDD"
			_log "WARN: You set it to '$NUM_HDD', which is not a correct syntax. Only digits are allowed."
			_log "WARN: Setting NUM_HDD to 0."
			NUM_HDD="0";
		}
if (( "$NUM_HDD" > 0 )); then
	for i in $(seq 1 $NUM_HDD); do
		eval HDD_SENSOR="\${HDD${i}}"
		if [ ! -z "$HDD_SENSOR_NAME" ]; then
			[[ -f /var/lib/rrdcached/db/localhost/$HDD_SENSOR ]] || {
				_log "WARN: given rrd-file in /var/lib/rrdcached/db/localhost for HDD${i} does not exist"
				eval _log "WARN: You set it to \${HDD${i}}"
				_log "WARN: Pleast check your config-file"
				_log "WARN: exiting script ..."
				f_end_section
			exit 1
			}
		fi
	done
	cp "$OMV_JSFILE_PLUGINDIR/HDDTemp.default" "$OMV_JSFILE_PLUGINDIR/HDDTemp.js"

	f_plugin_hddtemp_header
	f_hdd_sensorsrrd
fi

f_end_section
exit 0